# Place this file in your project's .github/workflows directory to enable it.
# Modify the addon name for auto-release as needed (in Step 3)

# Note: You need to set up workflow permissions in your Github project:
# Settings -> Actions -> General -> Workflow permissions -> Add read and write permissions for this workflow

name: Release Addon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Release addon
        run: python release.py glb_tools --with_version --with_timestamp
      - name: Upload release
        uses: actions/upload-artifact@v3
        with:
          name: addon-release
          path: ../addon_release/*.zip

# Add additional steps for each addon as needed... Add other addon release commands in the following format